blank: blank.template.txt
	mkdir blank
	cp $< blank/Makefile

naturalstories: natural_stories.template.txt
	mkdir naturalstories
	cp $< naturalstories/Makefile

%: blank.template.txt
	mkdir $@
	cp $< $@/Makefile
