#!/usr/bin/bash
#PBS -l walltime=96:00:00
#PBS -l nodes=1:ppn=32,mem=128GB
#PBS -j oe
#PBS -m abe
#PBS -M clark.3664@osu.edu

source ~/.bashrc
conda activate gpt2_env
scripts_dir=/home/clark.3664/git/modelblocks-release/resource-gpt2/scripts
models_dir=/home/clark.3664/git/gpt-2/models
model=124M
input=/home/clark.3664/git/modelblocks-release/resource-gpt2/sentence.txt
output=/home/clark.3664/gpt2_example_out.itemmeasures

python3 $scripts_dir/per_word_surprisal.py $input --models_dir $models_dir --model_name $model > $output

